---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage-management/get-v1-organizations-capacitypolicies-.html'
summary: 'Retrieve a capacity policy in NetApp Console local deployment'
---

= Retrieve a capacity policy in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/v1/organizations/{organizationId}/capacitypolicies/{capacityPolicyId}`#



Retrieves the specified capacity policy.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organizationId
|string
|path
|True
a|Organization ID

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|capacityPolicyId
|string
|path
|True
a|Capacity policy ID

* example: 123e4567-e89b-12d3-a456-426614174000


|===

== Response

```
Status: 200, Successfully retrieved capacity policy
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|autoGrow
|string
|False
a|Auto-grow setting of the capacity policy.


|description
|string
|False
a|Description of the capacity policy.


|id
|string
|True
a|Unique identifier of the capacity policy.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|True
a|Name of the capacity policy.


|organizationId
|string
|False
a|Organization ID that the policy is associated with.


|policyType
|string
|False
a|Type of the capacity policy.


|spaceReserved
|string
|False
a|Space reservation setting of the capacity policy.


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) associated with the capacity policy. Can be used to add any additional data related to the capacity policy.


|tiering
|string
|False
a|Tiering setting of the capacity policy.


|type
|string
|False
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.capacitypolicy"


|version
|string
|False
a|Version of the resource schema.
Defined values are:

* "1.0"


|volumeType
|string
|False
a|Volume type setting of the capacity policy.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "autoGrow": "GROW",
  "description": "Policy for production workloads with auto-grow and tiering",
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2024-01-15T10:30:00.000Z",
    "labels": [],
    "modificationTimestamp": "2024-01-20T14:45:00.000Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  },
  "name": "Production Capacity Policy",
  "organizationId": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "policyType": "USER_DEFINED",
  "spaceReserved": "THIN",
  "tags": [
    {
      "internal:bxp:metric:associatedWorkloadCnt": "2"
    }
  ],
  "tiering": "AUTO",
  "type": "application/vnd.netapp.bxp.capacitypolicy",
  "version": "1.0",
  "volumeType": "FLEXVOL"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
