---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage-management/get-v1-organizations-protectionpolicies-.html'
summary: 'Retrieve protection policy details in NetApp Console local deployment'
---

= Retrieve protection policy details in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/v1/organizations/{organizationId}/protectionpolicies/{protectionPolicyId}`#



Retrieves the details of the specified protection policy.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organizationId
|string
|path
|True
a|Organization ID


|protectionPolicyId
|string
|path
|True
a|Protection Policy ID

* example: 4fa85f64-5717-4562-b3fc-2c963f66afa7


|===

== Response

```
Status: 200, Successfully retrieved protection policy details.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|description
|string
|False
a|Description of the protection policy.


|id
|string
|True
a|Unique identifier of the protection policy.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|True
a|Name of the protection policy.


|organizationId
|string
|False
a|Organization ID that the policy is associated with.


|policyType
|string
|False
a|Type of the protection policy.


|snapshotSchedules
|array[link:#snapshotSchedules[snapshotSchedules]]
|False
a|An array of snapshot schedules defined in the protection policy.


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) associated with the protection policy. Can be used to add any additional data related to the protection policy.


|type
|string
|False
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.protectionpolicy"


|version
|string
|False
a|Version of the resource schema.
Defined values are:

* "1.0"


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "description": "Daily snapshot policy with 7 day retention",
  "id": "4fa85f64-5717-4562-b3fc-2c963f66afa7",
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  },
  "name": "Daily Backup Policy",
  "organizationId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "policyType": "USER_DEFINED",
  "snapshotSchedules": [
    {
      "retentionCount": 7,
      "schedule": "DAILY"
    },
    {
      "retentionCount": 4,
      "schedule": "WEEKLY"
    }
  ],
  "tags": [
    {
      "internal:bxp:metric:associatedWorkloadCnt": "2"
    }
  ],
  "type": "application/vnd.netapp.bxp.protectionpolicy",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#snapshotSchedules]
[.api-collapsible-fifth-title]
snapshotSchedules

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|retentionCount
|integer
|False
a|Number of snapshots to retain.


|schedule
|string
|False
a|Type of schedule for snapshots.


|===


[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
