---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage-management/patch-v1-organizations-storageclasses-.html'
summary: 'Update an existing storage class in NetApp Console local deployment'
---

= Update an existing storage class in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/v1/organizations/{organizationId}/storageclasses/{storageClassId}`#



Updates a storage class by using its unique identifier within the specified organization.

Update is only allowed when:

* no workloads are associated with the storage class.
* storageClassType is 'user-defined'.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|storageClassId
|string
|path
|True
a|Unique identifier of the storage class to update.


|organizationId
|string
|path
|True
a|Unique identifier of the organization.


|===

== Request Body

Expected to contain properties to be updated for the storage class.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|capacityPolicy
|string
|False
a|Capacity policy ID associated with the storage class.


|description
|string
|False
a|Description of the storage class.


|name
|string
|False
a|Name of the storage class.
This name must be unique within the specific organization.


|performancePolicy
|string
|False
a|Performance policy ID associated with the storage class.


|protectionPolicies
|array[string]
|False
a|List of protection policies associated with the storage class.


|securityPolicy
|string
|False
a|Security policy ID associated with the storage class.


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) associated with the storage class. Can be used to add any additional data related to the storage class.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.storageclass"


|version
|string
|True
a|Version of the resource schema.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "capacityPolicy": "b336b8c1-b388-43e4-8f85-4ca84121ebda",
  "description": "Configuration for extreme performance on workloads",
  "name": "Extreme Performance",
  "performancePolicy": "494a3e48-812a-4204-8450-32aa6aaf1c5f",
  "protectionPolicies": [
    "92a8fc02-3bd2-4e1f-b034-521ca42ddabf"
  ],
  "securityPolicy": "188714a5-6687-4410-83c3-7214f2943b2d",
  "tags": [
    {
      "internal:bxp:metric:associatedWorkloadCnt": "5"
    }
  ],
  "type": "application/vnd.netapp.bxp.storageclass",
  "version": "1.0"
}
====

== Response

```
Status: 204, Storage class updated successfully.
```

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
