---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage-management/patch-v1-organizations-protectionpolicies-.html'
summary: 'Update a protection policy in NetApp Console local deployment'
---

= Update a protection policy in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/v1/organizations/{organizationId}/protectionpolicies/{protectionPolicyId}`#



Modifies an existing protection policy. Include only the fields you want to update in the request.
The protection policy can only be modified if there is no workload associated with it and it is not system-defined.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organizationId
|string
|path
|True
a|Organization ID


|protectionPolicyId
|string
|path
|True
a|Protection policy ID

* example: 4fa85f64-5717-4562-b3fc-2c963f66afa7


|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|description
|string
|False
a|Protection policy description.


|name
|string
|False
a|Protection policy name.


|snapshotSchedules
|array[link:#snapshotSchedules[snapshotSchedules]]
|False
a|Array of snapshot schedule objects used to create local snapshot policies.


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) associated with the performance policy. Can be used to add any additional data related to the performance policy.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.protectionpolicy"


|version
|string
|True
a|Version of the resource schema.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "name": "New Policy Name",
  "snapshotSchedules": [
    {
      "retentionCount": 48,
      "schedule": "HOURLY"
    },
    {
      "retentionCount": 7,
      "schedule": "DAILY"
    }
  ]
}
====

== Response

```
Status: 204, Protection policy updated successfully.
```

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#snapshotSchedules]
[.api-collapsible-fifth-title]
snapshotSchedules

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|retentionCount
|integer
|True
a|Number of snapshots to be retained for a schedule.


|schedule
|string
|True
a|Snapshot schedule frequency.


|===


[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
