---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/get-organizations-serviceaccounts-publickeys.html'
summary: 'List all the public keys for a service account in NetApp Console local deployment'
---

= List all the public keys for a service account in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/organizations/{organization_id}/serviceaccounts/{serviceaccount_id}/publickeys`#



Lists all public keys for the specified service account.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Organization ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|serviceaccount_id
|string
|path
|True
a|Service account ID.

* example: 118df263-44d0-4154-8daa-ff61cb471557


|===

== Response

```
Status: 200, List of all public keys for the service account.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|items
|array[link:#user_1_0_public_key_get_response_body[user_1.0_public_key_get_response_body]]
|True
a|JSON array containing the resource objects returned for the current page of the collection.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "items": [
    {
      "audience": "https://netapp-cloud-account.auth0.com/",
      "credentialId": "cred_fh4agpsm4BphW5QZiYhHR8",
      "expirationTimestamp": "2026-06-24T16:25:08Z",
      "fingerprint": "33:0E:66:6A:D0:89:EA:78:10:7D:5A:35:FF:C5:51:E9:3A:CB:47:A8",
      "id": "4336388b-2992-43af-81de-ba9284b7dc36",
      "keyType": "RSA_KEY",
      "metadata": {
        "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
        "creationTimestamp": "2022-10-06T20:58:16.305662Z",
        "labels": [
          {
            "name": "string",
            "value": "string"
          }
        ],
        "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
        "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
      },
      "state": "ENABLED",
      "type": "application/vnd.netapp.bxp.publickey",
      "version": "1.0"
    }
  ]
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#user_1_0_public_key_get_response_body]
[.api-collapsible-fifth-title]
user_1.0_public_key_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|audience
|string
|False
a|The value that must be included in the "audience" claim of the private key JWT token.


|credentialId
|string
|False
a|The Auth0 credential ID associated with the public key.


|expirationTimestamp
|string
|False
a|The date and time when the public key expires.


|fingerprint
|string
|False
a|The SHA-1 fingerprint of the public X.509 certificate or RSA key that was provided for the public key.


|id
|string
|True
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|keyType
|string
|False
a|Type of the public key.
Defined values are:

* "X509_CERTIFICATE" - The public key is an X.509 certificate.
* "RSA_KEY" - The public key is an RSA key.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|state
|string
|False
a|The state of the public key. Defined values are:

* "ENABLED" - The public key is enabled.
* "DISABLED" - The public key is disabled.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.publickey"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


//end collapsible .Definitions block
====
