---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/get-users-resources-permissions.html'
summary: 'List all permissions a user has for a resource in NetApp Console local deployment'
---

= List all permissions a user has for a resource in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/users/{user_id}/resources/{resource_id}/permissions`#



Lists all permissions a user has for the specified resource.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|user_id
|string
|path
|True
a|User ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|resource_id
|string
|path
|True
a|Resource ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|filter
|string
|query
|False
a|Specifies which fields should be matched when listing tenancy resources.

Supported operators:

* eq - Equality
* ne - Not equal
* lt/gt - Less than/greater than
* lte/gte - Less than or equal to/greater than or equal to
* in - Membership test
* ex - Existence check

Expressions can be chained with `and` or `or` to build complex filters and
grouped with parentheses for precedence control.

URL example: "filter=resourceType%20eq%20'organization'%20or%20state%20ne%20'INACTIVE'"

URL example with grouping: "filter=(resourceType%20eq%20'organization'%20or%20state%20ne%20'INACTIVE')%20and%20tier%20gt%20'1'"

OpenAPI examples: "resourceType eq 'organization' and state ne 'INACTIVE'"


|skip
|string
|query
|False
a|Specifies the number of resources to skip when listing a collection.

URL examples: "skip=1"

OpenAPI examples: "1"


|include
|string
|query
|False
a|Specifies which fields should be returned when listing a collection.

URL examples: "include=id", "include=id,name"

OpenAPI examples: "id"


|limit
|string
|query
|False
a|Specifies the maximum number of resources to return when listing a collection.

URL examples: "limit=2"

OpenAPI examples: "2"


|orderBy
|string
|query
|False
a|Indicates the sort order of resources when listing a collection.

URL examples: "orderBy=name", "orderBy=name%20desc"

OpenAPI examples: "name desc"


|count
|string
|query
|False
a|Indicates if the total number of resources should be returned in the response object.

URL examples: "count=true"

OpenAPI examples: "true"


|continue
|string
|query
|False
a|Indicates the token to resume from when listing a collection.

URL examples: "continue=[Continue Token from Collection Metadata]"

OpenAPI examples: "[Continue Token from Collection Metadata]"


|===

== Response

```
Status: 200, List of all permissions.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|continue
|string
|False
a|Pagination cursor for resuming the list from the next page. Only returned when more results exist beyond the current page. Pass this value back as the `continue` query parameter on the next request.


|count
|int
|False
a|Total number of resources matching the query, independent of pagination.


|items
|array[Any of: link:#permission_1_0_get_response_body[permission_1.0_get_response_body], array[]]
|True
a|

|metadata
|link:#type_bxp_metadata_list[type_bxp_metadata_list]
|False
a|Metadata associated with a list of resources.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "items": [
    {
      "description": "Added permission which allow user to read in aiq",
      "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "metadata": {
        "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
        "creationTimestamp": "2022-10-06T20:58:16.305662Z",
        "labels": [],
        "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
        "modifiedby": "8f84cf09-8036-51e4-b579-bd30cb07b269"
      },
      "rule": "aiq:system-read",
      "serviceApplication": "aiq",
      "type": "application/vnd.netapp.bxp.permission",
      "version": "1.0"
    },
    {
      "description": "Added permission which allow user to read in aiq",
      "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "metadata": {
        "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
        "creationTimestamp": "2022-10-06T20:58:16.305662Z",
        "labels": [],
        "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
        "modifiedby": "8f84cf09-8036-51e4-b579-bd30cb07b269"
      },
      "rule": "bxp:organization-read",
      "serviceApplication": "bxp",
      "type": "application/vnd.netapp.bxp.permission",
      "version": "1.0"
    }
  ]
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#accept-post]
[.api-collapsible-fifth-title]
accept-post

Provides details about which media types are accepted when creating a resource.



[#accept-put]
[.api-collapsible-fifth-title]
accept-put

Indicates details about what media types are accepted when updating a resource.



[#hints]
[.api-collapsible-fifth-title]
hints

Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|accept-post
|link:#accept-post[accept-post]
|False
a|Provides details about which media types are accepted when creating a resource.


|accept-put
|link:#accept-put[accept-put]
|False
a|Indicates details about what media types are accepted when updating a resource.


|allow
|array[string]
|False
a|An array of methods that can be used to interact with the link target.

Defined values for collections:

"POST" - Indicates if new resources can be created in the collection.
Defined values for resources:

"PUT" - Indicates if the resource can be modified
"DELETE" - Indicates if the resource can be deleted


|permissions
|array[string]
|False
a|List of the permissions required to use the link.


|status
|string
|False
a|Indicates if the target of the link is deprecated.

Defined values are:

"deprecated"


|===


[#targetSchema]
[.api-collapsible-fifth-title]
targetSchema

Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.



[#type_bxp_link]
[.api-collapsible-fifth-title]
type_bxp_link

Link relationship


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hints
|link:#hints[hints]
|False
a|Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


|href
|string
|True
a|String describing a relative URI.


|rel
|string
|True
a|The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.


|targetSchema
|link:#targetSchema[targetSchema]
|False
a|Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.


|title
|string
|False
a|Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry).

Minimum length: 0
Maximum length: 1023


|type
|string
|False
a|The media type of the target of the href.

This field is optional and should be included when there is a known media type for the target of the href.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.


|===


[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#permission_1_0_get_response_body]
[.api-collapsible-fifth-title]
permission_1.0_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|description
|string
|False
a|JSON string containing the description of the permission. Defined values are: * Minimum length: 1 * Maximum length: 254 * This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|isSystem
|string
|False
a|Specifies if an object is system generated.
Defined values are:

* "true"


|links
|array[link:#type_bxp_link[type_bxp_link]]
|False
a|Array of link relationships associated with the resource or collection.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|rule
|string
|True
a|JSON string containing the permission in the format [serviceApplication]:[resourceType]-[action][-[modifier]].
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|service_application
|string
|True
a|JSON string containing the serviceApplication associated with this permission.


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) representing metadata for the permission.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.permission"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


[#type_bxp_metadata_list]
[.api-collapsible-fifth-title]
type_bxp_metadata_list

Metadata associated with a list of resources.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|count
|number
|False
a|

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


//end collapsible .Definitions block
====
