---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/get-resources-permissions-users.html'
summary: 'List all users with a specific permission for a resource in NetApp Console local deployment'
---

= List all users with a specific permission for a resource in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/resources/{resource_id}/permissions/{permission_id}/users`#



Lists all users with a specific permission for the specified resource.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|resource_id
|string
|path
|True
a|Resource ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|permission_id
|string
|path
|True
a|Permission ID.

* example: 118df263-44d0-4154-8daa-ff61cb471557


|filter
|string
|query
|False
a|Specifies which fields should be matched when listing tenancy resources.

Supported operators:

* eq - Equality
* ne - Not equal
* lt/gt - Less than/greater than
* lte/gte - Less than or equal to/greater than or equal to
* in - Membership test
* ex - Existence check

Expressions can be chained with `and` or `or` to build complex filters and
grouped with parentheses for precedence control.

URL example: "filter=resourceType%20eq%20'organization'%20or%20state%20ne%20'INACTIVE'"

URL example with grouping: "filter=(resourceType%20eq%20'organization'%20or%20state%20ne%20'INACTIVE')%20and%20tier%20gt%20'1'"

OpenAPI examples: "resourceType eq 'organization' and state ne 'INACTIVE'"


|skip
|string
|query
|False
a|Specifies the number of resources to skip when listing a collection.

URL examples: "skip=1"

OpenAPI examples: "1"


|include
|string
|query
|False
a|Specifies which fields should be returned when listing a collection.

URL examples: "include=id", "include=id,name"

OpenAPI examples: "id"


|limit
|string
|query
|False
a|Specifies the maximum number of resources to return when listing a collection.

URL examples: "limit=2"

OpenAPI examples: "2"


|orderBy
|string
|query
|False
a|Indicates the sort order of resources when listing a collection.

URL examples: "orderBy=name", "orderBy=name%20desc"

OpenAPI examples: "name desc"


|count
|string
|query
|False
a|Indicates if the total number of resources should be returned in the response object.

URL examples: "count=true"

OpenAPI examples: "true"


|continue
|string
|query
|False
a|Indicates the token to resume from when listing a collection.

URL examples: "continue=[Continue Token from Collection Metadata]"

OpenAPI examples: "[Continue Token from Collection Metadata]"


|===

== Response

```
Status: 200, List of users that have the permission on the resource.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|continue
|string
|False
a|Pagination cursor for resuming the list from the next page. Only returned when more results exist beyond the current page. Pass this value back as the `continue` query parameter on the next request.


|count
|integer
|False
a|

|items
|array[link:#user_1_0_get_response_body[user_1.0_get_response_body]]
|True
a|JSON array containing the resource objects returned for the current page of the collection.


|metadata
|link:#type_bxp_metadata_list[type_bxp_metadata_list]
|False
a|Metadata associated with a list of resources.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "continue": "string",
  "count": 1,
  "items": [
    {
      "aadId": "8cb0fe27-484b-4226-a19b-9d8811f6fb6a",
      "auth0Id": "KBX6WeLgdwlmGyte01rm6Mvc7J-vYwyXHLL5jjtRltM",
      "description": "This user is part of NetApp Sales Territory",
      "editable": "string",
      "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "isSystem": "true",
      "legacyId": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "links": [
        {
          "hints": {
            "allow": [
              "string"
            ],
            "permissions": [
              "string"
            ],
            "status": "string"
          },
          "href": "string",
          "rel": "string",
          "title": "string",
          "type": "string"
        }
      ],
      "metadata": {
        "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
        "creationTimestamp": "2022-10-06T20:58:16.305662Z",
        "labels": [
          {
            "name": "string",
            "value": "string"
          }
        ],
        "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
        "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
      },
      "name": "string",
      "ownerOrganizationId": "string",
      "partner": "string",
      "serviceAccount": {
        "audience": "https://netapp-cloud-account.auth0.com/",
        "authenticationMethod": "PRIVATE_KEY_JWT",
        "expirationNotificationPeriod": "P30D",
        "publicKeys": [
          {
            "audience": "https://netapp-cloud-account.auth0.com/",
            "expirationTimestamp": "2026-06-24T16:25:08Z",
            "fingerprint": "33:0E:66:6A:D0:89:EA:78:10:7D:5A:35:FF:C5:51:E9:3A:CB:47:A8",
            "id": "4336388b-2992-43af-81de-ba9284b7dc36",
            "keyType": "X509_CERTIFICATE",
            "metadata": {
              "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
              "creationTimestamp": "2025-06-24T16:25:08Z",
              "modificationTimestamp": "2025-06-24T16:25:08Z",
              "modifiedBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
            },
            "state": "ENABLED",
            "type": "application/vnd.netapp.bxp.publickey+json",
            "version": "1.0"
          }
        ]
      },
      "state": "ACTIVE",
      "tags": [
        "object"
      ],
      "type": "application/vnd.netapp.bxp.user",
      "userType": "serviceAccount",
      "version": "1.0"
    }
  ],
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [
      {
        "name": "string",
        "value": "string"
      }
    ],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#accept-post]
[.api-collapsible-fifth-title]
accept-post

Provides details about which media types are accepted when creating a resource.



[#accept-put]
[.api-collapsible-fifth-title]
accept-put

Indicates details about what media types are accepted when updating a resource.



[#hints]
[.api-collapsible-fifth-title]
hints

Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|accept-post
|link:#accept-post[accept-post]
|False
a|Provides details about which media types are accepted when creating a resource.


|accept-put
|link:#accept-put[accept-put]
|False
a|Indicates details about what media types are accepted when updating a resource.


|allow
|array[string]
|False
a|An array of methods that can be used to interact with the link target.

Defined values for collections:

"POST" - Indicates if new resources can be created in the collection.
Defined values for resources:

"PUT" - Indicates if the resource can be modified
"DELETE" - Indicates if the resource can be deleted


|permissions
|array[string]
|False
a|List of the permissions required to use the link.


|status
|string
|False
a|Indicates if the target of the link is deprecated.

Defined values are:

"deprecated"


|===


[#targetSchema]
[.api-collapsible-fifth-title]
targetSchema

Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.



[#type_bxp_link]
[.api-collapsible-fifth-title]
type_bxp_link

Link relationship


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hints
|link:#hints[hints]
|False
a|Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


|href
|string
|True
a|String describing a relative URI.


|rel
|string
|True
a|The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.


|targetSchema
|link:#targetSchema[targetSchema]
|False
a|Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.


|title
|string
|False
a|Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry).

Minimum length: 0
Maximum length: 1023


|type
|string
|False
a|The media type of the target of the href.

This field is optional and should be included when there is a known media type for the target of the href.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.


|===


[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#user_1_0_public_key_get_response_body]
[.api-collapsible-fifth-title]
user_1.0_public_key_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|audience
|string
|False
a|The value that must be included in the "audience" claim of the private key JWT token.


|credentialId
|string
|False
a|The Auth0 credential ID associated with the public key.


|expirationTimestamp
|string
|False
a|The date and time when the public key expires.


|fingerprint
|string
|False
a|The SHA-1 fingerprint of the public X.509 certificate or RSA key that was provided for the public key.


|id
|string
|True
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|keyType
|string
|False
a|Type of the public key.
Defined values are:

* "X509_CERTIFICATE" - The public key is an X.509 certificate.
* "RSA_KEY" - The public key is an RSA key.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|state
|string
|False
a|The state of the public key. Defined values are:

* "ENABLED" - The public key is enabled.
* "DISABLED" - The public key is disabled.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.publickey"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


[#serviceAccount]
[.api-collapsible-fifth-title]
serviceAccount

Properties specific to users with userType=serviceAccount. The audience, expirationNotificationPeriod, and publicKeys properties are only applicable when authenticationMethod=PRIVATE_KEY_JWT.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|audience
|string
|False
a|The value that must be included in the "audience" claim of the private key JWT token.


|authenticationMethod
|string
|False
a|Authentication method used by the service account.
Defined values are:

* "CLIENT_SECRET" - Service account uses a client ID and secret to authenticate when requesting an access token.
* "PRIVATE_KEY_JWT" - Service account uses a JWT token signed with a private key to authenticate when requesting an access token.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|publicKeys
|array[link:#user_1_0_public_key_get_response_body[user_1.0_public_key_get_response_body]]
|False
a|List of public keys associated with the service account.


|===


[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#user_1_0_get_response_body]
[.api-collapsible-fifth-title]
user_1.0_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|aadId
|string
|False
a|User AAD ID.


|auth0Id
|string
|False
a|User auth0 ID.


|description
|string
|False
a|JSON string containing the description of the user. Defined values are: * Minimum length: 1 * Maximum length: 300 * This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|editable
|string
|False
a|Partner organization is editable or not.


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|isSystem
|string
|False
a|Specifies if an object is system generated.
Defined values are:

* "true"


|legacyId
|string
|False
a|Unique identifier as understood by the previous version of this service.


|links
|array[link:#type_bxp_link[type_bxp_link]]
|False
a|Array of link relationships associated with the resource or collection.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|User name.


|ownerOrganizationId
|string
|True
a|JSON string containing the ID of the organization.


|partner
|string
|False
a|Partner organization name.


|serviceAccount
|link:#serviceAccount[serviceAccount]
|False
a|Properties specific to users with userType=serviceAccount. The audience, expirationNotificationPeriod, and publicKeys properties are only applicable when authenticationMethod=PRIVATE_KEY_JWT.


|state
|string
|False
a|Current state of the user.
Defined values are:

_**_ "ACTIVE"

_**_ "INACTIVE"


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) representing metadata for the user.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.user"


|userType
|string
|False
a|Type of user.


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


[#type_bxp_metadata_list]
[.api-collapsible-fifth-title]
type_bxp_metadata_list

Metadata associated with a list of resources.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|count
|number
|False
a|

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


//end collapsible .Definitions block
====
