---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/post-folders-resourcegroups.html'
summary: 'Add resource groups to a folder in NetApp Console local deployment'
---

= Add resource groups to a folder in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/folders/{folder_id}/resourcegroups`#



Adds resource groups to the specified folder.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|folder_id
|string
|path
|True
a|Folder ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|===

== Request Body

Indicates the resource groups to be added.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|resourcegroups
|array[link:#resourcegroups[resourcegroups]]
|True
a|

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.resourcegroupbulk"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "description": "adding StorageAdmin resourcegroup",
  "resourcegroups": [
    {
      "id": "a94ac68f-ea20-47aa-add8-8d41be0d8466"
    },
    {
      "name": "StorageAdmin"
    }
  ],
  "type": "application/vnd.netapp.bxp.resourcegroupbulk",
  "version": "1.0"
}
====

== Response

```
Status: 202, Indicates that the resourcegroup request was accepted.
```

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#resourcegroups]
[.api-collapsible-fifth-title]
resourcegroups

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|False
a|JSON string containing a name for the resource group.
Defined values are:

* Minimum length: 1
* Maximum length: 300
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
