---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/post-resourcetypes.html'
summary: 'Create a new resource type in NetApp Console local deployment'
---

= Create a new resource type in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/resourcetypes`#



Indicates the desired values for the ResourceType API resource to be created. You need to specify at least resourceClass, resourceType and description. If this Resource Class/Type is a translation for a legacy Class/Type, the legacyResourceClass and legacyResourceType fields should contain the associated legacy values.


== Request Body

Indicates the desired values for the ResourceType API resource to be created.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|description
|string
|True
a|JSON string containing the description of this resourceType. Defined values are: * Minimum length: 1 * Maximum length: 254 * This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|isSystem
|string
|False
a|Specifies if an object is system generated.
Defined values are:

* "true"


|legacyResourceClass
|string
|False
a|JSON string containing the legacy resource class (for example: "ON_PREM", "CAPACITY_BASED_LICENSE", ...) associated with the new resource class/type record.
If a resource class/type is new, the value for legacyResourceClass and legacyResourceType is null.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|legacyResourceType
|string
|False
a|JSON string containing the legacy resource type (for example: "ON_PREM", "AWS", ...) associated with the new resource class/type record.
If a resource class/type is new, the value for legacyResourceClass and legacyResourceType is null.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|resourceClass
|string
|True
a|JSON string containing the resource class (for example: "internal", "license", ...). This is case-sensitive and should be provided in lowercase.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|resourceType
|string
|True
a|JSON string containing the resource type under a resource class (for example: "capacity", "cluster", ...). This is case-sensitive and should be provided in lowercase.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.resourcetype"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "description": "Represent a Customer Organization",
  "resourceClass": "hierarchy",
  "resourceType": "organization",
  "type": "application/vnd.netapp.bxp.resourcetype",
  "version": "1.0"
}
====

== Response

```
Status: 201, Returns the newly created resourcetype resource in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|description
|string
|False
a|JSON string containing the description of this resourceType. Defined values are: * Minimum length: 1 * Maximum length: 254 * This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|isSystem
|string
|False
a|Specifies if an object is system generated.
Defined values are:

* "true"


|legacyResourceClass
|string
|False
a|JSON string containing the legacy resource class (for example: "ON_PREM", "CAPACITY_BASED_LICENSE", ...) associated with the new resource class/type record.
If a resource class/type is new, the value for legacyResourceClass and legacyResourceType is null.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|legacyResourceType
|string
|False
a|JSON string containing the legacy resource type (for example: "ON_PREM", "AWS", ...) associated with the new resource class/type record.
If a resource class/type is new, the value for legacyResourceClass and legacyResourceType is null.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|links
|array[link:#type_bxp_link[type_bxp_link]]
|False
a|Array of link relationships associated with the resource or collection.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|True
a|Metadata associated with the resource.


|resourceClass
|string
|True
a|JSON string containing the resource class (for example: "internal", "license", ...). This is case-sensitive and should be provided in lowercase.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|resourceType
|string
|True
a|JSON string containing the resource type under a resource class (for example: "capacity", "cluster", ...). This is case-sensitive and should be provided in lowercase.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.resourcetype"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "description": "Represent a Customer Organization",
  "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "metadata": {
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z"
  },
  "resourceClass": "hierarchy",
  "resourceType": "organization",
  "type": "application/vnd.netapp.bxp.resourcetype",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#accept-post]
[.api-collapsible-fifth-title]
accept-post

Provides details about which media types are accepted when creating a resource.



[#accept-put]
[.api-collapsible-fifth-title]
accept-put

Indicates details about what media types are accepted when updating a resource.



[#hints]
[.api-collapsible-fifth-title]
hints

Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|accept-post
|link:#accept-post[accept-post]
|False
a|Provides details about which media types are accepted when creating a resource.


|accept-put
|link:#accept-put[accept-put]
|False
a|Indicates details about what media types are accepted when updating a resource.


|allow
|array[string]
|False
a|An array of methods that can be used to interact with the link target.

Defined values for collections:

"POST" - Indicates if new resources can be created in the collection.
Defined values for resources:

"PUT" - Indicates if the resource can be modified
"DELETE" - Indicates if the resource can be deleted


|permissions
|array[string]
|False
a|List of the permissions required to use the link.


|status
|string
|False
a|Indicates if the target of the link is deprecated.

Defined values are:

"deprecated"


|===


[#targetSchema]
[.api-collapsible-fifth-title]
targetSchema

Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.



[#type_bxp_link]
[.api-collapsible-fifth-title]
type_bxp_link

Link relationship


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hints
|link:#hints[hints]
|False
a|Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


|href
|string
|True
a|String describing a relative URI.


|rel
|string
|True
a|The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.


|targetSchema
|link:#targetSchema[targetSchema]
|False
a|Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.


|title
|string
|False
a|Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry).

Minimum length: 0
Maximum length: 1023


|type
|string
|False
a|The media type of the target of the href.

This field is optional and should be included when there is a known media type for the target of the href.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
