---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/post-organizations-serviceaccounts-publickeys.html'
summary: 'Create a public key for a service account in NetApp Console local deployment'
---

= Create a public key for a service account in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/organizations/{organization_id}/serviceaccounts/{serviceaccount_id}/publickeys`#



Creates a public key for the specified service account.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Organization ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|serviceaccount_id
|string
|path
|True
a|Service account ID.

* example: 118df263-44d0-4154-8daa-ff61cb471557


|===

== Request Body

Indicates the desired values for the public key to be created.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|expirationTimestamp
|string
|False
a|The date and time when the public key expires. This is only applicable when an RSA key is provided for  the public key. When a certificate is provided, the value is set to the certificate's expiration timestamp.


|publicKey
|string
|True
a|Public X.509 certificate or RSA key in PEM format converted to a string with escaped new line characters (`
`).


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.publickey"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "expirationTimestamp": "2026-06-24T16:25:08Z",
  "publicKey": "-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0B... -----END PUBLIC KEY----- ",
  "type": "application/vnd.netapp.bxp.publickey",
  "version": "1.0"
}
====

== Response

```
Status: 201, Returns information about the newly created public key in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|audience
|string
|True
a|The value that must be included in the "audience" claim of the private key JWT token.


|expirationTimestamp
|string
|True
a|The date and time when the public key expires.


|fingerprint
|string
|True
a|The SHA-1 fingerprint of the public X.509 certificate or RSA key that was provided for the public key.


|id
|string
|True
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|keyType
|string
|True
a|Type of the public key.
Defined values are:

* "X509_CERTIFICATE" - The public key is an X.509 certificate.
* "RSA_KEY" - The public key is an RSA key.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|True
a|Metadata associated with the resource.


|state
|string
|True
a|The state of the public key. Defined values are:

* "ENABLED" - The public key is enabled.
* "DISABLED" - The public key is disabled.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.publickey"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "audience": "https://netapp-cloud-account.auth0.com/",
  "expirationTimestamp": "2026-06-24T16:25:08Z",
  "fingerprint": "33:0E:66:6A:D0:89:EA:78:10:7D:5A:35:FF:C5:51:E9:3A:CB:47:A8",
  "id": "4336388b-2992-43af-81de-ba9284b7dc36",
  "keyType": "RSA_KEY",
  "metadata": {
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
    "creationTimestamp": "2025-06-24T16:25:08Z",
    "modificationTimestamp": "2025-06-24T16:25:08Z",
    "modifiedBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  },
  "state": "ENABLED",
  "type": "application/vnd.netapp.bxp.publickey+json",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
