---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/post-roles-permissions.html'
summary: 'Add a list of permissions to a role in NetApp Console local deployment'
---

= Add a list of permissions to a role in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/roles/{role_id}/permissions`#



Adds a list of permissions to the specified role.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|role_id
|string
|path
|True
a|Role ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|===

== Request Body

Indicates the desired values for the permissions to be added to a role.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|permissions
|array[string]
|True
a|JSON array of permission UUIDs.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.permissionbulk"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "permissions": [
    "a94ac68f-ea20-47aa-add8-8d41be0d8466",
    "b04ac68f-da27-578a-cee8-9e45bq0d8466"
  ],
  "type": "application/vnd.netapp.bxp.permissionbulk",
  "version": "1.0"
}
====

== Response

```
Status: 202, Indicates the permissions request was accepted.
```

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
