---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/put-users-.html'
summary: 'Modify a user in NetApp Console local deployment'
---

= Modify a user in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/users/{user_id}`#



Replaces the specified user with new information.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|user_id
|string
|path
|True
a|User ID.

* example: 666a3f38-d4fa-5b62-a391-a69029758d32


|===

== Request Body

Replaces the entire stored resource with the supplied JSON request body while preserving the key values that are not user-modifiable.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|aadId
|string
|False
a|User AAD ID.


|auth0Id
|string
|False
a|User auth0 ID.


|description
|string
|False
a|JSON string containing the description of the user. Defined values are: * Minimum length: 1 * Maximum length: 300 * This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|isSystem
|string
|False
a|Specifies if an object is system generated.
Defined values are:

* "true"


|legacyId
|string
|False
a|Unique identifier as understood by the previous version of this service.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|User name.


|ownerOrganizationId
|string
|True
a|JSON string containing the ID of the organization.


|password
|string
|False
a|User password in plain text.


|serviceAccount
|link:#serviceAccount[serviceAccount]
|False
a|Properties specific to users with userType=serviceAccount. The expirationNotificationPeriod,  expirationTimestamp, and publicKey properties are only applicable when authenticationMethod=PRIVATE_KEY_JWT.


|stateDesired
|string
|False
a|Expected state of the user.
Defined values are:

***** "CREATE"

***** "UPDATE"


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) representing metadata for the user.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.user"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "auth0Id": "waad|KBX6WeLgdwlmGyte01rm6Mvc7J-vYwyXHLL5jjtRltM",
  "description": "Adding user to NetApp Sales Territory",
  "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "isServiceAccount": false,
  "metadata": {
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  },
  "name": "user-1",
  "password": "********",
  "stateDesired": "UPDATE",
  "tags": [
    {
      "internal:bxp:organizationId": "777a3f38-d4fa-5b62-a391-a69029758d32"
    }
  ],
  "type": "application/vnd.netapp.bxp.user",
  "version": "1.0"
}
====

== Response

```
Status: 200, Indicates if the user was updated.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|aadId
|string
|False
a|User AAD ID.


|auth0ClientSecret
|string
|False
a|Auth0 Client Secret.


|auth0Id
|string
|False
a|User auth0 ID.


|description
|string
|False
a|JSON string containing the description of the user. Defined values are: * Minimum length: 1 * Maximum length: 300 * This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|isSystem
|string
|False
a|Specifies if an object is system generated.
Defined values are:

* "true"


|legacyId
|string
|False
a|Unique identifier as understood by the previous version of this service.


|links
|array[link:#type_bxp_link[type_bxp_link]]
|False
a|Array of link relationships associated with the resource or collection.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|User name.


|ownerOrganizationId
|string
|True
a|JSON string containing the ID of the organization.


|serviceAccount
|link:#serviceAccount[serviceAccount]
|False
a|Properties specific to users with userType=serviceAccount. The audience, expirationNotificationPeriod, and publicKeys properties are only applicable when authenticationMethod=PRIVATE_KEY_JWT.


|state
|string
|False
a|Current state of the user.
Defined values are:

_**_ "ACTIVE"

_**_ "INACTIVE"


|tags
|array[link:#tags[tags]]
|False
a|JSON array of tags (name/value pairs) representing metadata for the user.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.user"


|userType
|string
|False
a|Type of user.


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "auth0Id": "waad|KBX6WeLgdwlmGyte01rm6Mvc7J-vYwyXHLL5jjtRltM",
  "description": "Adding user to NetApp Sales Territory",
  "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "metadata": {
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  },
  "name": "user-1",
  "state": "ACTIVE",
  "tags": [
    {
      "internal:bxp:folderId": "777a3f38-d4fa-5b62-a391-a69029758d32"
    }
  ],
  "type": "application/vnd.netapp.bxp.user",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#serviceAccount]
[.api-collapsible-fifth-title]
serviceAccount

Properties specific to users with userType=serviceAccount. The expirationNotificationPeriod,  expirationTimestamp, and publicKey properties are only applicable when authenticationMethod=PRIVATE_KEY_JWT.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|authenticationMethod
|string
|True
a|Authentication method used by the service account.
Defined values are:

* "CLIENT_SECRET" - Service account uses a client ID and secret to authenticate when requesting an access token.
* "PRIVATE_KEY_JWT" - Service account uses a JWT token signed with a private key to authenticate when requesting an access token.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|expirationTimestamp
|string
|False
a|The date and time when the public key expires. This is only applicable when an RSA key is provided for  the public key. When a certificate is provided, the value is set to the certificate's expiration timestamp.


|publicKey
|string
|False
a|Public X.509 certificate or RSA key in PEM format converted to a string with escaped new line characters (`
`).


|===


[#tags]
[.api-collapsible-fifth-title]
tags
Hash mapping strings to string

[#accept-post]
[.api-collapsible-fifth-title]
accept-post

Provides details about which media types are accepted when creating a resource.



[#accept-put]
[.api-collapsible-fifth-title]
accept-put

Indicates details about what media types are accepted when updating a resource.



[#hints]
[.api-collapsible-fifth-title]
hints

Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|accept-post
|link:#accept-post[accept-post]
|False
a|Provides details about which media types are accepted when creating a resource.


|accept-put
|link:#accept-put[accept-put]
|False
a|Indicates details about what media types are accepted when updating a resource.


|allow
|array[string]
|False
a|An array of methods that can be used to interact with the link target.

Defined values for collections:

"POST" - Indicates if new resources can be created in the collection.
Defined values for resources:

"PUT" - Indicates if the resource can be modified
"DELETE" - Indicates if the resource can be deleted


|permissions
|array[string]
|False
a|List of the permissions required to use the link.


|status
|string
|False
a|Indicates if the target of the link is deprecated.

Defined values are:

"deprecated"


|===


[#targetSchema]
[.api-collapsible-fifth-title]
targetSchema

Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.



[#type_bxp_link]
[.api-collapsible-fifth-title]
type_bxp_link

Link relationship


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hints
|link:#hints[hints]
|False
a|Provides details about how a link can be interacted with, such as allowed methods, required permissions, and accepted media types for create/update operations.


|href
|string
|True
a|String describing a relative URI.


|rel
|string
|True
a|The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.


|targetSchema
|link:#targetSchema[targetSchema]
|False
a|Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.


|title
|string
|False
a|Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry).

Minimum length: 0
Maximum length: 1023


|type
|string
|False
a|The media type of the target of the href.

This field is optional and should be included when there is a known media type for the target of the href.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.


|===


[#user_1_0_public_key_get_response_body]
[.api-collapsible-fifth-title]
user_1.0_public_key_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|audience
|string
|False
a|The value that must be included in the "audience" claim of the private key JWT token.


|credentialId
|string
|False
a|The Auth0 credential ID associated with the public key.


|expirationTimestamp
|string
|False
a|The date and time when the public key expires.


|fingerprint
|string
|False
a|The SHA-1 fingerprint of the public X.509 certificate or RSA key that was provided for the public key.


|id
|string
|True
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|keyType
|string
|False
a|Type of the public key.
Defined values are:

* "X509_CERTIFICATE" - The public key is an X.509 certificate.
* "RSA_KEY" - The public key is an RSA key.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|state
|string
|False
a|The state of the public key. Defined values are:

* "ENABLED" - The public key is enabled.
* "DISABLED" - The public key is disabled.


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.publickey"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


[#serviceAccount]
[.api-collapsible-fifth-title]
serviceAccount

Properties specific to users with userType=serviceAccount. The audience, expirationNotificationPeriod, and publicKeys properties are only applicable when authenticationMethod=PRIVATE_KEY_JWT.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|audience
|string
|False
a|The value that must be included in the "audience" claim of the private key JWT token.


|authenticationMethod
|string
|False
a|Authentication method used by the service account.
Defined values are:

* "CLIENT_SECRET" - Service account uses a client ID and secret to authenticate when requesting an access token.
* "PRIVATE_KEY_JWT" - Service account uses a JWT token signed with a private key to authenticate when requesting an access token.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|publicKeys
|array[link:#user_1_0_public_key_get_response_body[user_1.0_public_key_get_response_body]]
|False
a|List of public keys associated with the service account.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
