---
sidebar: sidebar
api: true
explorer: false
permalink: 'alerts/get-organizations-fleets-alerts.html'
summary: 'List all alerts for a fleet in NetApp Console local deployment'
---

= List all alerts for a fleet in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/organizations/{organization_id}/fleets/{fleet_id}/alerts`#



Lists all alerts for the specified fleet.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Unique identifier of the organization to which the user belongs.


|fleet_id
|string
|path
|True
a|Unique identifier of the fleet.


|filter
|string
|query
|False
a|Specifies which fields should be matched in order to return a resource when listing a collection.

Supported operators:

* eq - Equality
* lt/gt - Less than/greater than
* lte/gte - Less than or equal to/greater than or equal to

URL example: "filter=field%20eq%20%27value%27"

OpenAPI examples: "field eq 'value'"


|skip
|string
|query
|False
a|Specifies the number of resources to skip when listing a collection.

URL examples: "skip=1"

OpenAPI examples: "1"


|include
|string
|query
|False
a|Specifies which fields should be returned when listing a collection.

URL examples: "include=id", "include=id,name"

OpenAPI examples: "id"


|limit
|string
|query
|False
a|Specifies the maximum number of resources to return when listing a collection.

URL examples: "limit=2"

OpenAPI examples: "2"


|orderBy
|string
|query
|False
a|Indicates the sort order of resources when listing a collection.

URL examples: "orderBy=name", "orderBy=name%20desc"

OpenAPI examples: "name desc"


|count
|string
|query
|False
a|Indicates if the total number of resources should be returned in the response object.

URL examples: "count=true"

OpenAPI examples: "true"


|continue
|string
|query
|False
a|Indicates the token to resume from when listing a collection.

URL examples: "continue=[Continue Token from Collection Metadata]"

OpenAPI examples: "[Continue Token from Collection Metadata]"


|===

== Response

```
Status: 200, List of all alerts for the fleet
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|count
|integer
|False
a|Total number of resources in the collection that match the query.


|items
|array[link:#alert_1_0_get_response_body[alert_1.0_get_response_body]]
|True
a|

|metadata
|link:#type_bxp_metadata_list[type_bxp_metadata_list]
|True
a|Metadata associated with a list of resources.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "count": 1,
  "items": [
    {
      "alertDetails": "Volume Vol1 is 90% used",
      "alertId": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "alertObjectId": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "alertObjectName": "Volume1",
      "alertObjectType": "CLUSTER",
      "associatedObjects": [
        {
          "objectId": "666a3f38-d4fa-5b62-a391-a69029758d32",
          "objectName": "string",
          "objectType": "string"
        }
      ],
      "closedOn": "2022-10-09T20:58:16.305Z",
      "description": "AutoSupport supports HTTPS, HTTP, and SMTP for transport protocols. Because of the sensitive nature of AutoSupport messages, NetApp strongly recommends using HTTPS as the default transport protocol for sending AutoSupport messages to NetApp support.",
      "driftAlert": false,
      "duration": "86400",
      "hasRemediation": true,
      "impactArea": "string",
      "lastTrueOccurrence": "2022-10-06T20:58:16.305Z",
      "links": [
        {
          "hints": {
            "allow": [
              "string"
            ],
            "permissions": [
              "string"
            ],
            "status": "string"
          },
          "href": "string",
          "rel": "string",
          "title": "string",
          "type": "string"
        }
      ],
      "metadata": {
        "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
        "creationTimestamp": "2022-10-06T20:58:16.305662Z",
        "labels": [
          {
            "name": "string",
            "value": "string"
          }
        ],
        "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
        "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
      },
      "name": "AutoSupport HTTPS Transport Disabled",
      "origin": "HARVEST",
      "originId": "333a3f38-a4fa-4e32-a371-a37027748a32",
      "owner": "John.Doe@akme.com",
      "raisedOn": "2022-10-06T20:58:16.305Z",
      "remediation": {
        "redirectURL": "https://www.xyz.com/",
        "text": "To set HTTPS as the transport protocol for AutoSupport messages, run the following ONTAP command: system node autosupport modify -transport https"
      },
      "resourceId": "OnPremWorkingEnvironment-382602e4-6d35-4eaf-93cc-8b62b1b594c8",
      "severity": "string",
      "status": "string",
      "statusHistory": [
        {
          "newStatus": "string",
          "oldStatus": "string",
          "timestamp": "2022-10-06T20:58:16.305Z"
        }
      ],
      "storageClassId": "666a3f38-d4fa-5b62-a391-a69029758d32",
      "storageClassName": "standard"
    }
  ],
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [
      {
        "name": "string",
        "value": "string"
      }
    ],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  }
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#associatedObjects]
[.api-collapsible-fifth-title]
associatedObjects

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|objectId
|string
|False
a|Unique identifier of the resource for which this alert is raised.


|objectName
|string
|False
a|The name of the object that is associated with the object on which the alert is raised.


|objectType
|string
|False
a|Type of the object on which the alert is raised. Defined values are:

** CLUSTER

** NODE

** AGGREGATE

** SVM

** VOLUME

** LUN

** DISK

** QTREE

** NVME_NAMESPACE

** SNAPMIRROR

** CIFS_SHARE

** NFS_SHARE

** CONNECTOR

** CONNECTOR_CONTAINER

** MSSQL_HOST

** ORACLE_HOST


|===


[#accept-post]
[.api-collapsible-fifth-title]
accept-post

Provides details about which media types are accepted when creating a resource.



[#accept-put]
[.api-collapsible-fifth-title]
accept-put

Indicates details about what media types are accepted when updating a resource.



[#hints]
[.api-collapsible-fifth-title]
hints

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|accept-post
|link:#accept-post[accept-post]
|False
a|Provides details about which media types are accepted when creating a resource.


|accept-put
|link:#accept-put[accept-put]
|False
a|Indicates details about what media types are accepted when updating a resource.


|allow
|array[string]
|False
a|An array of methods that can be used to interact with the link target.

Defined values for collections:

"POST" - Indicates if new resources can be created in the collection.
Defined values for resources:

"PUT" - Indicates if the resource can be modified
"DELETE" - Indicates if the resource can be deleted


|permissions
|array[string]
|False
a|List of the permissions required to use the link.


|status
|string
|False
a|Indicates if the target of the link is deprecated.

Defined values are:

"deprecated"


|===


[#targetSchema]
[.api-collapsible-fifth-title]
targetSchema

Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.



[#type_bxp_link]
[.api-collapsible-fifth-title]
type_bxp_link

Link relationship


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hints
|link:#hints[hints]
|False
a|

|href
|string
|True
a|String describing a relative URI.


|rel
|string
|True
a|The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.


|targetSchema
|link:#targetSchema[targetSchema]
|False
a|Link to a JSON schema that can be used to validate the target of the link (response body).

The preferred format is a $ref link to an external schema.

This field is optional and should only be included when there is a known schema for the target of the href.

See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.


|title
|string
|False
a|Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry).

Minimum length: 0
Maximum length: 1023


|type
|string
|False
a|The media type of the target of the href.

This field is optional and should be included when there is a known media type for the target of the href.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.


|===


[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#remediation]
[.api-collapsible-fifth-title]
remediation

JSON object containing text that describes corrective actions about how to fix the issue
and an optional URL to navigate to the remedial workflow.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|redirectURL
|string
|False
a|URL that can be invoked to initiate the remediation.


|text
|string
|False
a|* example: To set HTTPS as the transport protocol for AutoSupport messages, run the following ONTAP command: system node autosupport modify -transport https


|===


[#statusHistory]
[.api-collapsible-fifth-title]
statusHistory

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|newStatus
|string
|False
a|JSON string representing the old status of this alert. It can be:

* CLOSED


|oldStatus
|string
|False
a|JSON string representing the old status of this alert. It can be:

* ACTIVE


|timestamp
|string
|False
a|Status change date


|===


[#tag]
[.api-collapsible-fifth-title]
tag

Key-value pairs providing additional context about the alert, such as metric name, threshold value, and unit.



[#alert_1_0_get_response_body]
[.api-collapsible-fifth-title]
alert_1.0_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|alertDetails
|string
|False
a|Details about the condition or situation that triggered this alert.


|alertId
|string
|True
a|Globally unique identifier of the resource, generated and assigned by the client service.


|alertObjectId
|string
|True
a|Unique identifier of the resource for which this alert is raised.


|alertObjectName
|string
|False
a|The name of the object on which the alert is raised.


|alertObjectType
|string
|True
a|Type of the object on which the alert is raised. Defined values are:

* CLUSTER
* NODE
* AGGREGATE
* SVM
* VOLUME
* LUN
* DISK
* QTREE
* NVME_NAMESPACE
* SNAPMIRROR
* CIFS_SHARE
* NFS_SHARE
* CONNECTOR
* CONNECTOR_CONTAINER
* MSSQL_HOST
* ORACLE_HOST


|associatedObjects
|array[link:#associatedObjects[associatedObjects]]
|True
a|JSON array of one or multiple contextual parent objects that might require remediation.
For example, an alert on a volume for an issue with junction path should populate this field with the SVM details because remediation has to be performed on the SVM.
Conversely, an alert on volume for low capacity should populate this field with the node details because remediation has to be performed on the node.


|closedOn
|string
|True
a|The time that the alert was closed.


|description
|string
|True
a|JSON string explaining the alert condition in detail.


|driftAlert
|boolean
|False
a|Indicates whether this alert was raised due to a configuration drift condition.


|duration
|string
|True
a|Duration that this alert is active, in milliseconds.


|hasRemediation
|boolean
|False
a|Indicates whether this alert has an associated remediation workflow.


|impactArea
|string
|True
a|Broad classification category to which this alert belongs. Examples of categories are:

* AVAILABILITY
* CAPACITY
* CONFIGURATION
* PERFORMANCE
* PROTECTION
* SECURITY


|lastTrueOccurrence
|string
|True
a|The time that the condition described by this alert was last found to be true. This value is a timestamp in ISO 8601 format in UTC.


|links
|array[link:#type_bxp_link[type_bxp_link]]
|False
a|Array of link relationships associated with the resource or ID.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|True
a|Metadata associated with the resource.


|name
|string
|True
a|Short name of the alert


|origin
|string
|True
a|Specifies the entity that raised this alert. Defined values are:

* HARVEST
* AIQ
* CONNECTOR
* ONTAP_MANAGEMENT
* BACKUP_AND_RECOVERY
* enum: ["HARVEST", "AIQ", "CONNECTOR", "ONTAP_MANAGEMENT", "BACKUP_AND_RECOVERY"]
* example: HARVEST


|originId
|string
|True
a|Globally unique identifier of alert source that is reporting this
alert. This originId along with the alertId is used to uniquely
identify the alert resource.


|owner
|string
|True
a|Action owner in the tenant organization


|raisedOn
|string
|True
a|The time that the alert was raised.


|remediation
|link:#remediation[remediation]
|True
a|JSON object containing text that describes corrective actions about how to fix the issue
and an optional URL to navigate to the remedial workflow.


|resourceId
|string
|False
a|Identifier of the working environment/resource associated with this alert.


|severity
|string
|True
a|Severity of the condition associated with this alert. Defined values are:

* CRITICAL
* WARNING
* INFORMATIONAL


|status
|string
|True
a|Status of the alert that shows whether the condition still exists. Defined values are:

* ACTIVE
* CLOSED


|statusHistory
|array[link:#statusHistory[statusHistory]]
|True
a|JSON array of JSON objects representing the chronological order of how this alert has progressed in its life cycle.


|storageClassId
|string
|False
a|Identifier of the storage class associated with this alert.


|storageClassName
|string
|False
a|Name of the storage class associated with this alert.


|tag
|link:#tag[tag]
|False
a|Key-value pairs providing additional context about the alert, such as metric name, threshold value, and unit.


|===


[#type_bxp_metadata_list]
[.api-collapsible-fifth-title]
type_bxp_metadata_list

Metadata associated with a list of resources.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|count
|number
|False
a|

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
