---
sidebar: sidebar
api: true
explorer: false
permalink: 'alerts/get-organizations-systems-alertsummary.html'
summary: 'Retrieve a summary of the alert counts for a system in NetApp Console local deployment'
---

= Retrieve a summary of the alert counts for a system in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/organizations/{organization_id}/systems/{system_id}/alertsummary`#



Retrieves an alert count summary for the specified system, grouped by impactArea and severity.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Unique identifier of the organization to which the user belongs.


|system_id
|string
|path
|True
a|Unique identifier of the system.


|===

== Response

```
Status: 200, Summary of the alert counts for the system, grouped by impactArea and severity.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|criticalImpactArea
|link:#criticalImpactArea[criticalImpactArea]
|True
a|Distribution of all critical alerts by impact area.


|impactArea
|link:#impactArea[impactArea]
|True
a|Distribution of all alerts by impact area.


|severity
|link:#severity[severity]
|True
a|Distribution of all alerts by severity.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "criticalImpactArea": {
    "capacity": 1,
    "performance": 2,
    "protection": 2,
    "security": 1
  },
  "impactArea": {
    "capacity": 1,
    "performance": 3,
    "protection": 5,
    "security": 1
  },
  "severity": {
    "critical": 6,
    "error": 7,
    "informational": 15,
    "warning": 8
  }
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#criticalImpactArea]
[.api-collapsible-fifth-title]
criticalImpactArea

Distribution of all critical alerts by impact area.

Hash mapping strings to integer

[#impactArea]
[.api-collapsible-fifth-title]
impactArea

Distribution of all alerts by impact area.

Hash mapping strings to integer

[#severity]
[.api-collapsible-fifth-title]
severity

Distribution of all alerts by severity.

Hash mapping strings to integer

[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
