---
sidebar: sidebar
api: true
explorer: false
permalink: 'asset/get-organizations-qtrees.html'
summary: 'List qtrees in an organization in NetApp Console local deployment'
---

= List qtrees in an organization in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/organizations/{organization_id}/qtrees`#



Lists all qtrees in the specified organization.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Identifier for an organization.


|count
|string
|query
|False
a|Indicates if the total number of resources should be returned in the response object.

URL examples: "count=true"

OpenAPI examples: "true"


|filter
|string
|query
|False
a|Specifies which fields should be matched in order to return a resource when listing a collection.

Supported operators:

* eq - Equality
* lt/gt - Less than/greater than
* lte/gte - Less than or equal to/greater than or equal to

URL example: "filter=field%20eq%20%27value%27"

OpenAPI examples: "field eq 'value'"


|include
|string
|query
|False
a|Specifies which fields should be returned when listing a collection.

URL examples: "include=id", "include=id,name"

OpenAPI examples: "id"


|limit
|string
|query
|False
a|Specifies the maximum number of resources to return when listing a collection.

URL examples: "limit=2"

OpenAPI examples: "2"


|metadata
|string
|query
|False
a|Indicates if the metadata should be returned in the response object.

URL examples: "metadata=true"

OpenAPI examples: "true"


|orderBy
|string
|query
|False
a|Indicates the sort order of resources when listing a collection.

URL examples: "orderBy=name", "orderBy=name%20desc"

OpenAPI examples: "name desc"


|skip
|string
|query
|False
a|Specifies the number of resources to skip when listing a collection.

URL examples: "skip=1"

OpenAPI examples: "1"


|===

== Response

```
Status: 200, OK
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|count
|integer
|False
a|Total number of resources in the collection that match the query.


|items
|array[link:#qtree_1_0_get_response_body[qtree_1.0_get_response_body]]
|True
a|Qtrees in the collection.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "count": 2,
  "items": [
    {
      "cluster": {
        "id": "4c8d2919-ac4c-4ea7-bf7c-24863d4da94b",
        "name": "cluster-01"
      },
      "exportPolicy": {
        "id": 123,
        "name": "default"
      },
      "files": {
        "hardLimit": 100000,
        "softLimit": 80000,
        "usedPercent": 45
      },
      "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "metadata": {
        "modificationTimestamp": "2024-03-15T10:22:31.123456Z"
      },
      "name": "qtree-01",
      "organizationId": "16c07c0c-666b-4870-9363-764eef9e7160",
      "path": "/volume-01/qtree-01",
      "quotaType": "TREE",
      "space": {
        "hardLimit": 10737418240,
        "softLimit": 8589934592,
        "usedPercent": 30
      },
      "svm": {
        "id": "d1ddc65d-f7a2-4ca7-9847-5afd069a3dbe",
        "name": "svm-01"
      },
      "type": "application/vnd.netapp.bxp.qtree",
      "version": "1.0",
      "volume": {
        "id": "8e2f9d4c-6a5b-4f8e-a2d7-5c9e4f2a7b8d",
        "name": "volume-01"
      },
      "workingEnvironmentId": "OnPremWorkingEnvironment-KxESQhek"
    },
    {
      "cluster": {
        "id": "4c8d2919-ac4c-4ea7-bf7c-24863d4da94b",
        "name": "cluster-01"
      },
      "exportPolicy": {
        "id": 456,
        "name": "nfs-export"
      },
      "files": {
        "hardLimit": 200000,
        "softLimit": 160000,
        "usedPercent": 60
      },
      "id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      "metadata": {
        "modificationTimestamp": "2024-03-15T11:45:09.654321Z"
      },
      "name": "qtree-02",
      "organizationId": "16c07c0c-666b-4870-9363-764eef9e7160",
      "path": "/volume-02/qtree-02",
      "quotaType": "USER",
      "space": {
        "hardLimit": 21474836480,
        "softLimit": 17179869184,
        "usedPercent": 45
      },
      "svm": {
        "id": "a7f19b3e-42c6-4d1a-9f7e-8b2d3c4e5f6a",
        "name": "svm-02"
      },
      "type": "application/vnd.netapp.bxp.qtree",
      "userOrGroup": "jsmith",
      "version": "1.0",
      "volume": {
        "id": "3a6d9f2c-5e8b-4f4a-c7d1-8e5a3d6f9c2e",
        "name": "volume-02"
      },
      "workingEnvironmentId": "OnPremWorkingEnvironment-KxESQhek"
    }
  ]
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#cluster_1_0_reference]
[.api-collapsible-fifth-title]
cluster_1.0_reference

Reference to an ONTAP cluster.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|Identifier of the cluster.


|name
|string
|False
a|Cluster name.


|===


[#exportPolicy]
[.api-collapsible-fifth-title]
exportPolicy

Export policy applied to the qtree.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|integer
|False
a|Identifier of the export policy.


|name
|string
|False
a|Name of the export policy.


|===


[#qtree_1_0_files]
[.api-collapsible-fifth-title]
qtree_1.0_files

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hardLimit
|integer
|False
a|The maximum number of files (inodes) allowed in the qtree.


|softLimit
|integer
|False
a|The soft limit on the number of files (inodes) in the qtree.


|usedPercent
|number
|False
a|The percentage of the files hard limit currently used by the qtree.


|===


[#common_1_0_inventory_metadata]
[.api-collapsible-fifth-title]
common_1.0_inventory_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|modificationTimestamp
|string
|False
a|Resource modification date.


|===


[#qtree_1_0_space]
[.api-collapsible-fifth-title]
qtree_1.0_space

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|hardLimit
|integer
|False
a|The hard limit on disk space usage by the qtree, in bytes.


|softLimit
|integer
|False
a|The soft limit on disk space usage by the qtree, in bytes.


|usedPercent
|number
|False
a|The percentage of the disk hard limit currently used by the qtree.


|===


[#svm_1_0_reference]
[.api-collapsible-fifth-title]
svm_1.0_reference

Reference to an ONTAP SVM.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|Identifier of the SVM.


|name
|string
|False
a|SVM name.


|===


[#volume_1_0_reference]
[.api-collapsible-fifth-title]
volume_1.0_reference

Reference to an ONTAP volume.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|Identifier of the volume.


|name
|string
|False
a|Volume name.


|===


[#qtree_1_0_get_response_body]
[.api-collapsible-fifth-title]
qtree_1.0_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|cluster
|link:#cluster_1_0_reference[cluster_1.0_reference]
|False
a|Reference to an ONTAP cluster.

* x-tag: Cluster


|exportPolicy
|link:#exportPolicy[exportPolicy]
|False
a|Export policy applied to the qtree.


|files
|link:#qtree_1_0_files[qtree_1.0_files]
|False
a|

|id
|string
|False
a|Identifier of the qtree.


|metadata
|link:#common_1_0_inventory_metadata[common_1.0_inventory_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|Qtree name.


|organizationId
|string
|False
a|Identifier for an organization.


|path
|string
|False
a|Client visible path to the qtree.


|quotaType
|string
|False
a|The type of quota applied to the qtree.
Defined values are:

* "TREE" - Quota applies to the entire qtree.
* "USER" - Quota applies to a specific user within the qtree.
* "GROUP" - Quota applies to a specific group within the qtree.


|space
|link:#qtree_1_0_space[qtree_1.0_space]
|False
a|

|svm
|link:#svm_1_0_reference[svm_1.0_reference]
|False
a|Reference to an ONTAP SVM.

* x-tag: SVM


|type
|string
|False
a|Media type of the resource.
Defined values are:

*** "application/vnd.netapp.bxp.qtree"


|userOrGroup
|string
|False
a|The name of the user or group the quota entry applies to. Populated when quotaType is USER or GROUP.


|version
|string
|False
a|Version of the resource.
Defined values are:

* "1.0"


|volume
|link:#volume_1_0_reference[volume_1.0_reference]
|False
a|Reference to an ONTAP volume.

* x-tag: Volume


|workingEnvironmentId
|string
|False
a|Identifier for the asset's system.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
