---
sidebar: sidebar
api: true
explorer: false
permalink: 'federation/post-organizations-federations.html'
summary: 'Create a new federation in NetApp Console local deployment'
---

= Create a new federation in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/organizations/{organization_id}/federations`#



Creates a new federation.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Identifier for an organization.


|===

== Request Body

Creates a new federation.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|autoAssignDefaultRoleIds
|array[string]
|False
a|Role IDs assigned on JIT first-login provision. View-only roles only - Max 5.


|autoAssignUsersEnabled
|boolean
|False
a|When true, Console auto-creates (JIT) a user identity and org membership


|domains
|array[string]
|False
a|Array of email domain names that are associated with the federation.

If a domain matches the user's email address or is an Entra ID `*.onmicrosoft.com` tenant domain, then it
does not need to be in a `VERIFIED` state. All other domains must be added to the domains
collection and be in a `VERIFIED` state.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|expirationTimestamp
|string
|False
a|Not applicable for LDAP federations.


|ldapOptions
|link:#federation_1_0_ldap_post_request_options[federation_1.0_ldap_post_request_options]
|False
a|Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


|name
|string
|True
a|The name of the federation.


|providerType
|string
|False
a|The type of the identity provider. Defined values are:

* "LDAP" - Lightweight Directory Access Protocol


|state
|string
|True
a|The state of the federation. Defined values are:

* "DRAFT" - The federation is partially configured.
* "CREATED" - The federation is configured but not tested.
* "ENABLED" - The federation is enabled (Allowed only in case of LDAP provider type).


|type
|string
|True
a|Media type of the resource.


|version
|string
|True
a|Version of the resource.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "domains": [
    "example.com",
    "example2.com"
  ],
  "name": "Draft Federation",
  "state": "DRAFT",
  "type": "application/vnd.netapp.bxp.federation",
  "version": "1.0"
}
====

== Response

```
Status: 201, Returns the newly created federation in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|auth0Id
|string
|False
a|The ID of the connection in Auth0.


|auth0Name
|string
|False
a|The name of the connection in Auth0.


|autoAssignDefaultRoleIds
|array[string]
|False
a|Identifier of roles assigned to first-time users automatically added to the organization


|autoAssignUsersEnabled
|boolean
|False
a|Whether first-time users should be automatically added to the organization when using this federation for SSO.


|domains
|array[string]
|False
a|Array of email domain names that are associated with the federation.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|expirationTimestamp
|string
|False
a|The date that the credentials or certificate expires. When a certificate is provided, the value is set to
the certificate's expiration timestamp.


|id
|string
|False
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|keycloakComponentId
|string
|False
a|Keycloak component identifier for LDAP provider.


|keycloakComponentName
|string
|False
a|Keycloak component name for LDAP provider.


|ldapOptions
|link:#federation_1_0_ldap_response_options[federation_1.0_ldap_response_options]
|False
a|Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|The name of the federation.


|organizationId
|string
|False
a|Identifier for an organization.


|providerType
|string
|False
a|The type of the identity provider. Defined values are:

* "LDAP" - Lightweight Directory Access Protocol


|resourceId
|string
|False
a|Identifier for the resource.


|state
|string
|False
a|The state of the federation. Defined values are:

* "DRAFT" - The federation is partially configured.
* "CREATED" - The federation is configured but not tested.
* "TESTED" - The federation has been successfully tested.
* "ENABLED" - The federation is enabled.
* "DISABLED" - The federation is disabled.


|type
|string
|False
a|Media type of the resource.


|version
|string
|False
a|Version of the resource.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "domains": [
    "example.com",
    "example2.com"
  ],
  "id": "645eae30-ea32-4542-af58-1d9012fed81a",
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  },
  "name": "Draft Federation",
  "organizationId": "9b0ee210-70a0-4158-b025-0decde66e4de",
  "resourceId": "862b6f03-58ac-479b-9ca5-5cb4429d8996",
  "state": "DRAFT",
  "type": "application/vnd.netapp.bxp.federation",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#federation_1_0_ldap_post_request_options]
[.api-collapsible-fifth-title]
federation_1.0_ldap_post_request_options

Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|bindCredential
|string
|True
a|Password for the bind DN.


|bindDn
|string
|True
a|Distinguished Name (DN) or UPN to bind to the LDAP server.


|connectionTimeout
|integer
|True
a|LDAP connection timeout, in milliseconds.


|connectionUrl
|string
|True
a|LDAP connection URL.


|importUsers
|boolean
|False
a|Indicates whether to import users from LDAP.


|pagination
|boolean
|False
a|Indicates whether to use LDAP pagination for user searches.


|rdnLdapAttribute
|string
|False
a|LDAP attribute used as Relative Distinguished Name (RDN).


|searchScope
|string
|False
a|LDAP search scope.


|syncRegistrations
|boolean
|False
a|Indicates whether to synchronize user registrations from LDAP.


|userObjectClasses
|string
|False
a|LDAP object class for users.


|usernameLdapAttribute
|string
|False
a|LDAP attribute used as username.


|usersDn
|string
|True
a|Base DN for user searches.


|uuidLdapAttribute
|string
|False
a|LDAP attribute used as universally unique identifier (UUID).


|===


[#federation_1_0_ldap_response_options]
[.api-collapsible-fifth-title]
federation_1.0_ldap_response_options

Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|bindCredential
|string
|False
a|Password for the bind DN.


|bindDn
|string
|False
a|Distinguished Name (DN) or UPN to bind to the LDAP server.


|connectionTimeout
|integer
|False
a|LDAP connection timeout, in milliseconds.


|connectionUrl
|string
|False
a|LDAP connection URL.


|importUsers
|boolean
|False
a|Indicates whether to import users from LDAP.


|pagination
|boolean
|False
a|Indicates whether to use LDAP pagination for user searches.


|rdnLdapAttribute
|string
|False
a|LDAP attribute used as Relative Distinguished Name (RDN).


|searchScope
|string
|False
a|LDAP search scope.


|syncRegistrations
|boolean
|False
a|Indicates whether to synchronize user registrations from LDAP.


|userObjectClasses
|string
|False
a|LDAP object class for users.


|usernameLdapAttribute
|string
|False
a|LDAP attribute used as username.


|usersDn
|string
|False
a|Base DN for user searches.


|uuidLdapAttribute
|string
|False
a|LDAP attribute used as universally unique identifier (UUID).


|===


[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
