---
sidebar: sidebar
api: true
explorer: false
permalink: 'federation/post-organizations-federations.html'
summary: 'Create a new federation in NetApp Console local deployment'
---

= Create a new federation in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/organizations/{organization_id}/federations`#



Creates a new federation.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Identifier for an organization.


|===

== Request Body

Creates a new federation.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|adfsOptions
|link:#federation_1_0_adfs_request_options[federation_1.0_adfs_request_options]
|False
a|Active Directory Federation Services (AD FS) configuration options when `providerType=ADFS`.
Either `metadataUrl` or `metadataFile` must be provided.


|autoAssignDefaultRoleIds
|array[string]
|False
a|Role IDs assigned on JIT first-login provision. View-only roles only - Max 5.


|autoAssignUsersEnabled
|boolean
|False
a|When true, Console auto-creates (JIT) a user identity and org membership


|domains
|array[string]
|False
a|Array of email domain names that are associated with the federation.

If a domain matches the user's email address or is an Entra ID `*.onmicrosoft.com` tenant domain, then it
does not need to be in a `VERIFIED` state. All other domains must be added to the domains
collection and be in a `VERIFIED` state.


|entraIdOptions
|link:#federation_1_0_entraid_post_request_options[federation_1.0_entraid_post_request_options]
|False
a|Microsoft Entra ID (formerly Azure Active Directory) configuration options when `providerType=ENTRAID`.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|expirationTimestamp
|string
|False
a|The date that the credentials expire. This is only applicable when `providerType=ENTRAID`. When a
certificate is provided for other provider types, the value is set to the certificate's expiration timestamp.


|ldapOptions
|link:#federation_1_0_ldap_post_request_options[federation_1.0_ldap_post_request_options]
|False
a|Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


|name
|string
|True
a|The name of the federation.


|pingFederateOptions
|link:#federation_1_0_pingfederate_post_request_options[federation_1.0_pingfederate_post_request_options]
|False
a|PingFederate configuration options when `providerType=PINGFEDERATE`.


|providerType
|string
|False
a|The type of the identity provider. Defined values are:

* "ADFS" - Active Directory Federation Services
* "ENTRAID" - Microsoft Entra ID (formerly Azure Active Directory)
* "PINGFEDERATE" - PingFederate
* "SAML" - Security Assertion Markup Language 2.0
* "LDAP" - Lightweight Directory Access Protocol


|samlOptions
|link:#federation_1_0_saml_post_request_options[federation_1.0_saml_post_request_options]
|False
a|SAML configuration options when `providerType=SAML`.


|state
|string
|True
a|The state of the federation. Defined values are:

* "DRAFT" - The federation is partially configured.
* "CREATED" - The federation is configured but not tested.
* "ENABLED" - The federation is enabled (Allowed only in case of LDAP provider type).


|type
|string
|True
a|Media type of the resource.


|version
|string
|True
a|Version of the resource.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "adfsOptions": {
    "metadataFile": "<?xml version='1.0'?> <EntityDescriptor xmlns='urn:oasis:names:tc:SAML:2.0:metadata'..."
  },
  "domains": [
    "example.com",
    "example2.com"
  ],
  "expirationNotificationPeriod": "P30D",
  "name": "AD FS Federation",
  "providerType": "ADFS",
  "state": "CREATED",
  "type": "application/vnd.netapp.bxp.federation",
  "version": "1.0"
}
====

== Response

```
Status: 201, Returns the newly created federation in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|adfsOptions
|link:#federation_1_0_adfs_response_options[federation_1.0_adfs_response_options]
|False
a|Active Directory Federation Services (AD FS) configuration options when `providerType=ADFS`.


|auth0Id
|string
|False
a|The ID of the connection in Auth0.


|auth0Name
|string
|False
a|The name of the connection in Auth0.


|autoAssignDefaultRoleIds
|array[string]
|False
a|Identifier of roles assigned to first-time users automatically added to the organization


|autoAssignUsersEnabled
|boolean
|False
a|Whether first-time users should be automatically added to the organization when using this federation for SSO.


|domains
|array[string]
|False
a|Array of email domain names that are associated with the federation.


|entraIdOptions
|link:#federation_1_0_entraid_response_options[federation_1.0_entraid_response_options]
|False
a|Microsoft Entra ID (formerly Azure Active Directory) configuration options when `providerType=ENTRAID`.


|expirationNotificationPeriod
|string
|False
a|The time period when expiration notifications are generated. Defined values are:

* "P7D" - Notifications are sent daily 7 days before expiration.
* "P30D" - Notifications are sent weekly 30 days before expiration. Notifications are sent daily 7 days before expiration.


|expirationTimestamp
|string
|False
a|The date that the credentials or certificate expires. When a certificate is provided, the value is set to
the certificate's expiration timestamp.


|id
|string
|False
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|keycloakComponentId
|string
|False
a|Keycloak component identifier for LDAP provider. For multi-OU federations,
populated with the primary (first, priority 0) component for backward
compatibility; see keycloakComponents for the full list.


|keycloakComponentName
|string
|False
a|Keycloak component name for LDAP provider. For multi-OU federations,
populated with the primary (first, priority 0) component for backward
compatibility; see keycloakComponents for the full list.


|keycloakComponents
|array[link:#federation_1_0_keycloak_component[federation_1.0_keycloak_component]]
|False
a|One entry per Keycloak LDAP UserStorageProvider component backing this
federation. Multi-OU federations have one component per OU; single-OU
federations have exactly one entry.


|ldapOptions
|link:#federation_1_0_ldap_response_options[federation_1.0_ldap_response_options]
|False
a|Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|The name of the federation.


|organizationId
|string
|False
a|Identifier for an organization.


|pingFederateOptions
|link:#federation_1_0_pingfederate_response_options[federation_1.0_pingfederate_response_options]
|False
a|PingFederate configuration options when `providerType=PINGFEDERATE`.


|providerType
|string
|False
a|The type of the identity provider. Defined values are:

* "ADFS" - Active Directory Federation Services
* "ENTRAID" - Microsoft Entra ID (formerly Azure Active Directory)
* "PINGFEDERATE" - PingFederate
* "SAML" - Security Assertion Markup Language 2.0
* "LDAP" - Lightweight Directory Access Protocol


|resourceId
|string
|False
a|Identifier for the resource.


|samlOptions
|link:#federation_1_0_saml_response_options[federation_1.0_saml_response_options]
|False
a|SAML configuration options when `providerType=SAML`.


|state
|string
|False
a|The state of the federation. Defined values are:

* "DRAFT" - The federation is partially configured.
* "CREATED" - The federation is configured but not tested.
* "TESTED" - The federation has been successfully tested.
* "ENABLED" - The federation is enabled.
* "DISABLED" - The federation is disabled.


|type
|string
|False
a|Media type of the resource.


|version
|string
|False
a|Version of the resource.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "adfsOptions": {
    "signingCertificateFingerprint": "33:0E:66:6A:D0:89:EA:78:10:7D:5A:35:FF:C5:51:E9:3A:CB:47:A8"
  },
  "auth0Id": "con_jxQFVfPHKSdiwoxs",
  "auth0Name": "fed-example-com-adfs",
  "domains": [
    "example.com",
    "example2.com"
  ],
  "expirationNotificationPeriod": "P30D",
  "expirationTimestamp": "2024-11-18T20:58:16.305662Z",
  "id": "645eae30-ea32-4542-af58-1d9012fed81a",
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  },
  "name": "AD FS Federation",
  "organizationId": "9b0ee210-70a0-4158-b025-0decde66e4de",
  "providerType": "ADFS",
  "resourceId": "862b6f03-58ac-479b-9ca5-5cb4429d8996",
  "state": "CREATED",
  "type": "application/vnd.netapp.bxp.federation",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Error

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409",
  "title": "JSON resource conflict",
  "type": "https://bluexp.netapp.io/problems/10"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#federation_1_0_adfs_request_options]
[.api-collapsible-fifth-title]
federation_1.0_adfs_request_options

Active Directory Federation Services (AD FS) configuration options when `providerType=ADFS`.
Either `metadataUrl` or `metadataFile` must be provided.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|metadataFile
|string
|False
a|JSON escaped contents of the Federation metadata XML file.


|metadataUrl
|string
|False
a|AD FS server URL for the Federation metadata XML file.


|===


[#federation_1_0_entraid_post_request_options]
[.api-collapsible-fifth-title]
federation_1.0_entraid_post_request_options

Microsoft Entra ID (formerly Azure Active Directory) configuration options when `providerType=ENTRAID`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|clientId
|string
|True
a|Entra ID client ID.


|clientSecret
|string
|True
a|Entra ID client secret.


|groupsEnabled
|boolean
|False
a|Indicates whether federation groups are enabled for Microsoft Entra ID.


|maxGroupCount
|integer
|False
a|Maximum number of groups to retrieve from Entra ID.


|tenantDomain
|string
|True
a|Entra ID domain.


|===


[#federation_1_0_ldap_post_request_options]
[.api-collapsible-fifth-title]
federation_1.0_ldap_post_request_options

Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|bindCredential
|string
|True
a|Password for the bind DN.


|bindDn
|string
|True
a|Distinguished Name (DN) or UPN to bind to the LDAP server.


|connectionTimeout
|integer
|True
a|LDAP connection timeout, in seconds.


|connectionUrl
|string
|True
a|LDAP connection URL.


|importUsers
|boolean
|False
a|Indicates whether to import users from LDAP.


|pagination
|boolean
|False
a|Indicates whether to use LDAP pagination for user searches.


|rdnLdapAttribute
|string
|False
a|LDAP attribute used as Relative Distinguished Name (RDN).


|searchScope
|string
|False
a|LDAP search scope.


|syncRegistrations
|boolean
|False
a|Indicates whether to synchronize user registrations from LDAP.


|userObjectClasses
|string
|False
a|LDAP object class for users.


|usernameLdapAttribute
|string
|False
a|LDAP attribute used as username.


|usersDn
|string
|False
a|Base DN for user searches in single-OU federations. Provide either usersDn
or usersDns, not both.


|usersDns
|array[string]
|False
a|List of base DNs for user searches, one entry per Organizational Unit (OU),
for multi-OU federations. Provide either usersDn or usersDns, not both. One
Keycloak LDAP component is created per entry, in list order (index 0 gets
priority 0, the highest lookup priority).


|uuidLdapAttribute
|string
|False
a|LDAP attribute used as universally unique identifier (UUID).


|===


[#federation_1_0_pingfederate_post_request_options]
[.api-collapsible-fifth-title]
federation_1.0_pingfederate_post_request_options

PingFederate configuration options when `providerType=PINGFEDERATE`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|serverUrl
|string
|True
a|PingFederate server URL.


|signingCertificate
|string
|True
a|X.509 signing certificate in PEM or CER format converted to a string with escaped new-line characters (`
`).


|===


[#federation_1_0_saml_post_request_options]
[.api-collapsible-fifth-title]
federation_1.0_saml_post_request_options

SAML configuration options when `providerType=SAML`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|signInUrl
|string
|True
a|SAML single login URL.


|signOutUrl
|string
|False
a|SAML single logout URL.


|signingCertificate
|string
|True
a|X.509 signing certificate in PEM or CER format converted to a string with escaped new-line characters (`
`).


|===


[#federation_1_0_adfs_response_options]
[.api-collapsible-fifth-title]
federation_1.0_adfs_response_options

Active Directory Federation Services (AD FS) configuration options when `providerType=ADFS`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|metadataUrl
|string
|False
a|AD FS server URL for the Federation metadata XML file.


|signingCertificateFingerprint
|string
|False
a|The SHA-1 fingerprint of the X.509 signing certificate if the metadata XML file is provided.


|===


[#federation_1_0_entraid_response_options]
[.api-collapsible-fifth-title]
federation_1.0_entraid_response_options

Microsoft Entra ID (formerly Azure Active Directory) configuration options when `providerType=ENTRAID`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|clientId
|string
|False
a|Entra ID client ID.


|clientSecretMasked
|string
|False
a|Partially masked Entra ID client secret.


|groupsEnabled
|boolean
|False
a|Indicates whether federation groups are enabled for Microsoft Entra ID.


|maxGroupCount
|integer
|False
a|Maximum number of groups to retrieve from Entra ID.


|tenantDomain
|string
|False
a|Entra ID domain.


|===


[#federation_1_0_keycloak_component]
[.api-collapsible-fifth-title]
federation_1.0_keycloak_component

A single Keycloak LDAP UserStorageProvider component backing one OU of a
federation. Entries are ordered ascending by priority (index 0 is priority
0, the highest lookup priority).


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|keycloakComponentId
|string
|False
a|Keycloak component identifier for this usersDn.


|keycloakComponentName
|string
|False
a|Keycloak component name for this usersDn.


|priority
|integer
|False
a|Lookup priority among sibling components (0 is highest / searched first).


|usersDn
|string
|False
a|Maps this Keycloak component to its usersDn in ldapOptions.usersDns for multi-OU federations.


|===


[#federation_1_0_ldap_response_options]
[.api-collapsible-fifth-title]
federation_1.0_ldap_response_options

Lightweight Directory Access Protocol (LDAP) configuration options when `providerType=LDAP`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|bindCredential
|string
|False
a|Password for the bind DN.


|bindDn
|string
|False
a|Distinguished Name (DN) or UPN to bind to the LDAP server.


|connectionTimeout
|integer
|False
a|LDAP connection timeout, in seconds.


|connectionUrl
|string
|False
a|LDAP connection URL.


|importUsers
|boolean
|False
a|Indicates whether to import users from LDAP.


|pagination
|boolean
|False
a|Indicates whether to use LDAP pagination for user searches.


|rdnLdapAttribute
|string
|False
a|LDAP attribute used as Relative Distinguished Name (RDN).


|searchScope
|string
|False
a|LDAP search scope.


|syncRegistrations
|boolean
|False
a|Indicates whether to synchronize user registrations from LDAP.


|userObjectClasses
|string
|False
a|LDAP object class for users.


|usernameLdapAttribute
|string
|False
a|LDAP attribute used as username.


|usersDn
|string
|False
a|Base DN for user searches (single usersDn federations). Populated with the
first/primary OU for backward compatibility when the federation has
multiple OUs; see usersDns for the full list.


|usersDns
|array[string]
|False
a|List of base DNs for user searches, one entry per Organizational Unit (OU),
for multi-OU federations. Not present for single-OU federations.


|uuidLdapAttribute
|string
|False
a|LDAP attribute used as universally unique identifier (UUID).


|===


[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#federation_1_0_pingfederate_response_options]
[.api-collapsible-fifth-title]
federation_1.0_pingfederate_response_options

PingFederate configuration options when `providerType=PINGFEDERATE`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|serverUrl
|string
|False
a|PingFederate server URL.


|signingCertificateFingerprint
|string
|False
a|The SHA-1 fingerprint of the X.509 Signing certificate.


|===


[#federation_1_0_saml_response_options]
[.api-collapsible-fifth-title]
federation_1.0_saml_response_options

SAML configuration options when `providerType=SAML`.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|signInUrl
|string
|False
a|SAML single login URL.


|signOutUrl
|string
|False
a|SAML single logout URL.


|signingCertificateFingerprint
|string
|False
a|The SHA-1 fingerprint of the X.509 Signing certificate.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
