---
sidebar: sidebar
api: true
explorer: false
permalink: 'agentic/get-supportedmodels-.html'
summary: 'Retrieve an LLM model in NetApp Console local deployment'
---

= Retrieve an LLM model in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/supportedModels/{supported_model_id}`#



Returns detailed information about a specific Large Language Model (LLM) model, identified by its unique ID.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|supported_model_id
|string
|path
|True
a|Unique identifier of the model or the model name.
Defined values are:

* Conforms to the UUIDv4 Schema
* example: 666a3f38-d4fa-5b62-a391-a69029758d32 or Claude 3 Opus


|===

== Response

```
Status: 200, Successfully retrieved the model.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|contextWindow
|integer
|False
a|Maximum context window size, in tokens.


|description
|string
|False
a|Human-readable description of the model.
Defined values are:

* Minimum length: 1
* Maximum length: 1024


|id
|string
|True
a|Globally unique identifier of the model.
Defined values are:

* Conforms to the UUIDv4 Schema


|isEnabled
|boolean
|False
a|Indicates whether this model is currently enabled for use.


|maxOutputTokens
|integer
|False
a|Maximum number of output tokens the model can generate.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|modelType
|string
|False
a|The type or category of the model.
Defined values are:

* "chat" - Chat completion models
* "completion" - Text completion models
* "embedding" - Embedding models
* "image" - Image generation models
* "audio" - Audio transcription/generation models
* "multimodal" - Models supporting multiple input/output types


|name
|string
|True
a|Name of the LLM model.
Defined values are:

* Minimum length: 1
* Maximum length: 254


|provider
|string
|False
a|The LLM provider that offers this model.
Defined values are:

* "openai" - OpenAI API
* "anthropic" - Anthropic Claude API
* "commonOpenAI" - Generic OpenAI-compatible API


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.supportedModel"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "contextWindow": 128000,
  "description": "OpenAI GPT-4o multimodal model with vision and audio capabilities",
  "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "isEnabled": true,
  "maxOutputTokens": 16384,
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [
      {
        "name": "string",
        "value": "string"
      }
    ],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  },
  "modelType": "chat",
  "name": "gpt-4o",
  "provider": "openai",
  "type": "application/vnd.netapp.bxp.supportedModel",
  "version": "1.0"
}
====

== Response

```
Status: 401, Unauthorized - authentication required.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 403, Forbidden - insufficient permissions.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 404, Not found - model does not exist.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 500, Internal server error.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Error

```
Status: 400, Bad request - invalid model id format.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
