---
sidebar: sidebar
api: true
explorer: false
permalink: 'agentic/get-configs-providermodels.html'
summary: 'List models available from a LLM provider associated with a saved configuration in NetApp Console local deployment'
---

= List models available from a LLM provider associated with a saved configuration in NetApp Console local deployment
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/configs/{config_id}/providerModels`#



Returns a list of all models available from the Large Language Model (LLM) provider associated
with the specified saved configuration.

This endpoint finds the configuration by using the `config_id`, retrieves the
stored provider credentials (API key, base URL, provider type, and so on) and
queries the provider's API directly to discover available models.

No request body is required -- all credentials are resolved from the saved
configuration record.

The response contains basic model information including name, provider,
and model type.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|config_id
|string
|path
|True
a|Unique identifier for the configuration instance.


|===

== Response

```
Status: 200, Successfully retrieved the list of models from the provider.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|count
|integer
|False
a|Number of items in the current response.


|items
|array[link:#providerModel_1_0_get_response_body[providerModel_1.0_get_response_body]]
|True
a|Array of provider model resources.


|type
|string
|True
a|Media type of the resource collection.
Defined values are:

* "application/vnd.netapp.bxp.providerModels"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "count": 3,
  "items": [
    {
      "modelType": "chat",
      "name": "gpt-4o",
      "provider": "openai",
      "supported": "true",
      "type": "application/vnd.netapp.bxp.providerModel",
      "version": "1.0"
    },
    {
      "modelType": "chat",
      "name": "gpt-4o-mini",
      "provider": "openai",
      "supported": "true",
      "type": "application/vnd.netapp.bxp.providerModel",
      "version": "1.0"
    },
    {
      "modelType": "embedding",
      "name": "text-embedding-3-large",
      "provider": "openai",
      "supported": "false",
      "type": "application/vnd.netapp.bxp.providerModel",
      "version": "1.0"
    }
  ],
  "type": "application/vnd.netapp.bxp.providerModels",
  "version": "1.0"
}
====

== Response

```
Status: 401, Unauthorized - authentication required or invalid provider credentials.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 403, Forbidden - insufficient permissions.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 404, Not found - no configuration exists with the given config_id.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 500, Internal server error.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Response

```
Status: 502, Bad gateway - failed to connect to the provider's api.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Error

```
Status: 400, Bad request - invalid config_id or configuration data.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#providerModel_1_0_get_response_body]
[.api-collapsible-fifth-title]
providerModel_1.0_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|modelType
|string
|False
a|Type or category of the model.
Defined values are:

* "chat" - Chat completion models
* "completion" - Text completion models
* "embedding" - Embedding models
* "image" - Image generation models
* "audio" - Audio transcription/generation models
* "multimodal" - Models supporting multiple input/output types


|name
|string
|True
a|Name or identifier of the model as returned by the provider's API.


|provider
|string
|True
a|Name of the LLM provider.
Defined values are:

* "openai" - OpenAI API
* "anthropic" - Anthropic Claude API
* "commonOpenAI" - Generic OpenAI-compatible API


|supported
|string
|False
a|JSON string that indicates if the model is supported by the Agentic Platform.
Defined values are:

* true
* false


|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/vnd.netapp.bxp.providerModel"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
